---
version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gal-commerce
    ports:
      - "5432:5432"
  # prism:
  #   image: stoplight/prism:4
  #   command: 'mock -h 0.0.0.0 /tmp/gal-commerce.oa.yml -d'
  #   volumes:
  #     - ./apps/api/docs:/tmp
  #   ports:
  #     # Serve the mocked API locally as available on port 4040
  #     - '8080:4010'
